name: Build and Deploy Documentation

on:
  push:
    branches: [ main, doc ]
  pull_request:
    branches: [ main, doc ]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[docs]
    
    - name: Build documentation
      run: |
        cd docs
        make html
    
    - name: Upload docs artifact
      uses: actions/upload-artifact@v3
      with:
        name: docs
        path: docs/_build/html/
    
    - name: Check for broken links
      run: |
        cd docs/_build/html
        python -m http.server 8000 &
        sleep 5
        pip install linkchecker
        linkchecker http://localhost:8000 --ignore-url=^http://localhost

  deploy-docs:
    needs: build-docs
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/doc'
    steps:
    - uses: actions/checkout@v4
    
    - name: Download docs artifact
      uses: actions/download-artifact@v3
      with:
        name: docs
        path: docs/_build/html/
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html
        publish_branch: gh-pages 